version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./prometheus:/etc/prometheus"

  grafana:
    image: grafana/grafana
    links:
      - prometheus:prometheus
    ports:
      - 3000:3000
    user: "104"
